---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}-jwks
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - '{{- printf "jwks-%s-%s.%s" .Chart.Name .Release.Namespace .Values.domain -}}'
  gateways:
    - teknoir/teknoir-gateway
  http:
    - route:
        - destination:
            host: jwks.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8083

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Chart.Name }}-jwks
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: jwks
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
      to:
        - operation:
            methods: ["GET"]

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Chart.Name }}-jwks
  namespace: {{ .Release.Namespace }}
spec:
  host: jwks.{{ .Release.Namespace }}.svc.cluster.local
  exportTo:
    - "teknoir"
    - "teknoir-system"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 1000
