---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-mpsrouter
  name: {{ .Chart.Name }}-mpsrouter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8003
    name: http-mpsrouter
    protocol: TCP
    targetPort: 8003
  selector:
    app: {{ .Chart.Name }}-mpsrouter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-mpsrouter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.mpsrouter.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-mpsrouter
  template:
    metadata:
{{/*      annotations:*/}}
{{/*        kuma.io/direct-access-services: "mps_default_svc_3000"*/}}
      labels:
        app: {{ .Chart.Name }}-mpsrouter
    spec:
{{/*      imagePullSecrets:*/}}
{{/*        - name: registrycredentials*/}}
      containers:
        - name: {{ .Chart.Name }}-mpsrouter
          securityContext:
            runAsUser: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          image:  {{ .Values.images.mpsrouter }}
          readinessProbe:
            exec:
              command: ["/app","--health"]
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: "MPS_CONNECTION_STRING"
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-mpsrouter
                  key: connectionString
            - name: "PORT"
              value: "8003"
            - name: "MPS_HOST"
              value: {{ .Chart.Name }}-mps
            - name: "MPS_PORT"
              value: "3000"
          ports:
            - containerPort: 8003
              name: http-mpsrouter
         
