---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-postgres
  name: {{ .Chart.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5432
    name: tcp-postgres
    protocol: TCP
    targetPort: 5432
  selector:
    app: {{ .Chart.Name }}-postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-postgres
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres
          securityContext:
            runAsUser: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          image:  {{ .Values.images.postgres }}
          readinessProbe:
            exec:
              command:
                - psql
                - -U
                - postgres
                - -d
                - rpsdb
                - -c
                - SELECT 1
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          env:
            - name: POSTGRES_DB
              value: rpsdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-postgres
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-postgres
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: tcp-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
