---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-rps
  name: {{ .Chart.Name }}-rps
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8080
    name: http-websockets
    protocol: TCP
    targetPort: 8080
  - port: 8081
    name: http-webapi
    protocol: TCP
    targetPort: 8081
  selector:
    app: {{ .Chart.Name }}-rps

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-rps
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.rps.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-rps
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-rps
    spec:
{{/*      imagePullSecrets:*/}}
{{/*        - name: registrycredentials*/}}
      containers:
        - name: {{ .Chart.Name }}-rps
          securityContext:
            runAsUser: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          image:  {{ .Values.images.rps }}
          readinessProbe:
            httpGet:
              path: /api/v1/admin/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: "RPS_LOG_LEVEL"
              value: "{{ .Values.rps.logLevel }}"
{{/*            - name: "RPS_VAULT_ADDRESS"*/}}
{{/*              value: "http://{{ .Release.Name }}-vault:8200"*/}}
            - name: "RPS_SECRETS_PATH"
              value: 'kv/data/'
            - name: "RPS_MPS_SERVER"
              value: "http://{{ .Chart.Name }}-mps:3000"
            - name: "RPS_CONNECTION_STRING"
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-rps
                  key: connectionString
{{/*            - name: RPS_VAULT_TOKEN*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: vault*/}}
{{/*                  key: vaultKey*/}}
          ports:
            - containerPort: 8080
              name: http-websockets
            - containerPort: 8081
              name: http-webapi
