apiVersion: v1
kind: Secret
metadata:
  name: mpsweb
type: Opaque
stringData:
  user: teknoir
  password: teknoir123456!#
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-rps
type: Opaque
stringData:
  connectionString: postgresql://<DATABASE-USERNAME>:<DATABASE-PASSWORD>@<DATABASE-SERVER-URL>:5432/rpsdb?sslmode=<SSL-MODE>
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mps
type: Opaque
stringData:
  connectionString: postgresql://<DATABASE-USERNAME>:<DATABASE-PASSWORD>@<DATABASE-SERVER-URL>:5432/mpsdb?sslmode=<SSL-MODE>
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mpsrouter
type: Opaque
stringData:
  connectionString: postgresql://<DATABASE-USERNAME>:<DATABASE-PASSWORD>@<DATABASE-SERVER-URL>:5432/mpsdb?sslmode=<SSL-MODE>
---
apiVersion: v1
kind: Secret
metadata:
  name: device-mgmt-toolkit-admin-jwt
type: Opaque
stringData:
  kongCredType: jwt
  key: admin-issuer
  algorithm: HS256
  secret: <YOUR-SECRET>


#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: device-mgmt-toolkit-admin-acl
#  labels:
#    konghq.com/credential: acl
#type: Opaque
#stringData:
#  kongCredType: acl
#  group: device-mgmt-toolkit-admin
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: vault
#  labels:
#    app: vault
#type: Opaque
#stringData:
#  vaultKey: <VAULT-ROOT-TOKEN>
#---